# GoReleaser config

---
builds:
- id: depbot_darwin
  binary: soda
  main: cmd/depbot/main.go
  goos:
    - darwin
  goarch:
    - amd64
  env:
    - CGO_ENABLED=1
    - CC=/osxcross/target/bin/o64-clang
    - CXX=/osxcross/target/bin/o64-clang++
  flags:
    - -tags
    - sqlite

- id: depbot_darwin_arm64
  binary: soda
  main: cmd/depbot/main.go
  goos:
    - darwin
  goarch:
    - arm64
  env:
    - CGO_ENABLED=1
    - CC=/osxcross/target/bin/oa64-clang
    - CXX=/osxcross/target/bin/oa64-clang++
  flags:
    - -tags
    - sqlite

- id: depbot_linux
  binary: soda
  main: cmd/depbot/main.go
  env:
    - CGO_ENABLED=0
  flags:
    - -tags
    - sqlite
  goos:
    - linux
  goarch:
    - amd64
    - 386

- id: depbot_windows_i686
  binary: soda
  main: cmd/depbot/main.go
  ldflags:
    - "-extldflags '-static'"
  env:
    - CGO_ENABLED=1
    - CC=i686-w64-mingw32-gcc
    - CXX=i686-w64-mingw32-g++
  flags:
    - -tags
    - sqlite
  goos:
    - windows
  goarch:
    - 386

- id: depbot_windows_x64
  binary: soda
  main: cmd/depbot/main.go
  ldflags:
    - "-extldflags '-static'"
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  flags:
    - -tags
    - sqlite
  goos:
    - windows
  goarch:
    - amd64

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'