name: Depbot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      - name: Downloading Depbot
        run: wget https://github.com/godepbot/depbot/releases/latest/download/depbot_linux_amd64.tar.gz
      - name: Extracting
        run: tar -xvzf depbot_linux_amd64.tar.gz
      - name: Setting up
        run: sudo mv depbot /usr/local/bin/depbot
      - name: Running Depbot
        run: /usr/local/bin/depbot list
