name: Depbot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Depbot
        run: go install github.com/godepbot/depbot/cmd/depbot@latest

      - name: Running Depbot
        run: depbot list
