name: Depbot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Installing Depbot
        run: wget https://github.com/godepbot/depbot/releases/latest/download/depbot_linux_amd64.tar.gz
        run: tar -xvzf depbot_linux_amd64.tar.gz
        run: sudo mv depbot /usr/local/bin/depbot
      - name: Running Depbot
        run: depbot list
